json_file: "jsons/HRTNET_S.json"
exp_name: big4_semantic_det2
data_path: "../DATASET/cityscapes/"
autodeeplab: "train_seg_panoptic"
seed: 12345
load_path: "fasterseg"
random_sample: False
eval_flag: True
opt: "sgd"
opt_eps: 0.001
sched: "new" #"raw for original"
epochs: 4000
drop_path_prob: 0.2
image_height: 512
image_width: 1024
eval_height: 1024
eval_width: 2048
batch_size: 2
mode: "poly"
base_lr: 0.05
Fch: 16
bn_momentum: 0.01
warmup_start_lr: 5e-6
warmup_iters: 1000
weight_decay: 1e-4
model_ema: False
model_ema_decay: 0.9998
clip_grad: 1.0
lamb: 0.2
ignore: 255
topk_percent: 0.2
semantic_loss_weight: 1.0
center_loss_weight: 200
offset_loss_weight: 0.01
sem_only: True
use_aux: True
align_corners: False
model_type: 1
